import { useEffect, useMemo, useState } from "react";
import "./App.css";

const API = "http://127.0.0.1:8000";
const formatINR = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
const prompts = ["Why am I losing revenue?", "Where am I losing money?", "What should I fix first?", "Which payments should I recover?"];

export default function App() {
  const [data, setData] = useState(null), [recovery, setRecovery] = useState(null);
  const [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [question, setQuestion] = useState(""), [copilot, setCopilot] = useState(null), [asking, setAsking] = useState(false);
  const [selected, setSelected] = useState(null), [states, setStates] = useState({});

  const load = async () => { setLoading(true); setError(""); try {
    const [i, r] = await Promise.all([fetch(`${API}/api/investigate`), fetch(`${API}/api/recovery`)]);
    if (!i.ok || !r.ok) throw new Error("API error");
    setData((await i.json()).investigation); setRecovery(await r.json());
  } catch (e) { console.error(e); setError("We could not load merchant intelligence. Check that the FastAPI server is running."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const ask = async (prompt) => { const q = (prompt || question).trim(); if (!q || asking) return; setQuestion(q); setAsking(true); try {
    const r = await fetch(`${API}/api/copilot`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: q }) });
    if (!r.ok) throw new Error("Copilot error"); setCopilot(await r.json());
  } catch (e) { console.error(e); setError("The copilot is temporarily unavailable. Please try again."); } finally { setAsking(false); } };
  const health = data ? Math.max(0, Math.round(100 - data.revenue_at_risk / data.total_revenue * 100)) : 0;
  const breakdown = useMemo(() => { if (!recovery) return []; const totals = recovery.top_opportunities.reduce((a, x) => ({ ...a, [x.payment_method]: (a[x.payment_method] || 0) + x.expected_recovery }), {}); const max = Math.max(...Object.values(totals), 1); return Object.entries(totals).map(([method, value]) => ({ method, value, width: value / max * 100 })); }, [recovery]);
  if (loading) return <div className="page-state"><i className="spinner" /><p>Loading merchant intelligence…</p></div>;
  if (!data || !recovery) return <div className="page-state"><h2>RevenueLens is unavailable</h2><p>{error}</p><button className="primary" onClick={load}>Try again</button></div>;
  const risk = Math.round(data.revenue_at_risk / data.total_revenue * 100);
  const update = (id, value) => setStates((s) => ({ ...s, [id]: value }));
  return <div className="app">
    <header><div><h1>RevenueLens <span>AI</span></h1><p>Merchant revenue recovery control center</p></div><b className="live"><i /> Intelligence ready</b></header>
    <main>
      {error && <div className="error" role="alert">{error}<button onClick={() => setError("")}>×</button></div>}
      <section className="hero"><div><label>REVENUE INTELLIGENCE</label><h2>Find the revenue your payments are leaving behind.</h2><p>Detect leakage, understand the cause, and prioritize the failed payments worth recovering.</p></div><a href="#recovery" className="primary">Review opportunities →</a></section>
      <section className="metrics"><Metric title="Total revenue" value={formatINR(data.total_revenue)} note="Processed revenue" /><Metric title="Revenue at risk" value={formatINR(data.revenue_at_risk)} note={`${risk}% of processed revenue`} type="risk" /><Metric title="Estimated recovery" value={formatINR(data.estimated_recovery)} note="Investigation estimate" type="good" /></section>
      <section className="two-col"><article className="card insight"><label>AI INSIGHT</label><h3>{data.primary_payment_method} payment degradation is strongest around {data.worst_hour}:00.</h3><div className="impact"><div><small>Impact</small><b>{formatINR(data.revenue_at_risk)} at risk</b></div><div><small>Recommended action</small><b>Review {data.primary_payment_method} failures and prioritize the ranked recovery queue.</b></div></div></article><article className="card health"><label>REVENUE HEALTH</label><strong>{health}<small>/100</small></strong><div className="progress"><i style={{ width: `${health}%` }} /></div><p>Payment performance is stable, with a focused leakage pattern to address.</p></article></section>
      <section className="visuals"><article className="card"><div className="heading"><div><label>RISK EXPOSURE</label><h3>Revenue health distribution</h3></div><b>{risk}%</b></div><div className="stack"><i style={{ width: `${100 - risk}%` }} /><em style={{ width: `${risk}%` }} /></div><p className="legend">● Protected revenue <span>● Revenue at risk</span></p></article><article className="card"><label>RECOVERY PIPELINE</label><h3>ML-ranked opportunity</h3><div className="pipeline"><div><b>{recovery.total_failed_transactions.toLocaleString()}</b><small>Failed transactions</small></div>→<div><b>{recovery.top_opportunities.length}</b><small>Priority queue</small></div>→<div><b>{formatINR(recovery.potential_recovery)}</b><small>Potential recovery</small></div></div></article><article className="card"><label>PAYMENT METHOD</label><h3>Recovery opportunity mix</h3><div className="breakdown">{breakdown.map((x) => <div key={x.method}><p><span>{x.method}</span><b>{formatINR(x.value)}</b></p><i><em style={{ width: `${x.width}%` }} /></i></div>)}</div><small>Based on the current ML-ranked queue.</small></article><article className="card time"><label>TIME-OF-DAY RISK</label><h3>{data.worst_hour}:00 is the highest-risk hour.</h3><div>{[9, 12, 15, 18, data.worst_hour, 22].map((x, i) => <span className={x === data.worst_hour ? "active" : ""} key={`${x}-${i}`}><i style={{ height: `${x === data.worst_hour ? 100 : 35 + i * 10}%` }} />{x}:00</span>)}</div><small>Highest recorded loss signal: {data.evening_hotspot} payments.</small></article></section>
      <section className="card copilot"><div className="heading"><div><label>AI MERCHANT COPILOT</label><h3>Ask about the money behind the metrics.</h3><p>Get a concise diagnosis, relevant insight, and the next action for your team.</p></div><b className="mark">RL</b></div><div className="prompts">{prompts.map((p) => <button key={p} onClick={() => ask(p)}>{p}</button>)}</div><div className="ask"><input value={question} onChange={(e) => setQuestion(e.target.value)} onKeyDown={(e) => e.key === "Enter" && ask()} placeholder="Ask a custom question…" aria-label="Question for RevenueLens Copilot" /><button className="primary" onClick={() => ask()} disabled={asking}>{asking ? "Analyzing…" : "Ask Copilot"}</button></div>{!copilot && !asking && <div className="empty">✦ <span><b>Your revenue analyst is ready.</b><br />Start with a suggested question or ask about a payment pattern.</span></div>}{asking && <div className="empty"><i className="spinner" /> RevenueLens is connecting the payment signals…</div>}{copilot && <div className="answer"><small>MERCHANT QUESTION</small><p>{copilot.question}</p><hr /><small>REVENUELENS ANALYSIS</small><h4>{copilot.answer}</h4><div><article><small>Next best action</small><b>{copilot.action}</b></article><article><small>Relevant insight</small><b>{copilot.insight.primary_payment_method} risk peaks at {copilot.insight.worst_hour}:00.</b></article></div><footer><span>Revenue at risk <b>{formatINR(copilot.metrics.revenue_at_risk)}</b></span><span>Potential recovery <b>{formatINR(copilot.metrics.potential_recovery)}</b></span></footer></div>}</section>
      <section className="card recovery" id="recovery"><div className="heading"><div><label>ML-POWERED RECOVERY</label><h3>Top recovery opportunities</h3><p>Ranked by expected recovery: transaction amount × predicted recovery probability.</p></div><b>{formatINR(recovery.potential_recovery)}<small>potential recovery</small></b></div><div className="table"><table><thead><tr><th>Transaction</th><th>Amount</th><th>Payment</th><th>Retries</th><th>Recovery</th><th>Expected value</th><th>Action</th></tr></thead><tbody>{recovery.top_opportunities.map((t) => <tr key={t.transaction_id}><td><b>{t.transaction_id}</b>{states[t.transaction_id] && <small className="status">{states[t.transaction_id] === "queued" ? "Recovery queued" : "Reviewed"}</small>}</td><td>{formatINR(t.amount)}</td><td><mark>{t.payment_method}</mark></td><td>{t.retry_count}</td><td className="good-text">{Math.round(t.recovery_probability * 100)}%</td><td><b>{formatINR(t.expected_recovery)}</b></td><td><button className="recover-btn" onClick={() => setSelected(t)}>Recover</button></td></tr>)}</tbody></table></div></section>
      <section className="card flow"><div><label>OPERATING FLOW</label><h3>Detect → Diagnose → Predict → Prioritize → Recover</h3><p>Every recovery recommendation stays in your team’s control. Queue actions are simulated in this prototype.</p></div><a href="#recovery" className="primary">Open recovery queue →</a></section>
    </main>
    {selected && <div className="overlay" onMouseDown={() => setSelected(null)}><section className="modal" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)} aria-label="Close">×</button><label>RECOVERY RECOMMENDATION</label><h2>Review {selected.transaction_id}</h2><div className="modal-grid"><Metric title="Amount" value={formatINR(selected.amount)} /><Metric title="Payment method" value={selected.payment_method} /><Metric title="Retry count" value={selected.retry_count} /><Metric title="Recovery probability" value={`${Math.round(selected.recovery_probability * 100)}%`} /><Metric title="Expected recovery" value={formatINR(selected.expected_recovery)} /></div><div className="recommend"><small>Recommended action</small><p>Retry payment using the same payment method after confirming the customer is ready to complete checkout.</p></div><div className="simulation"><b>Prototype simulation</b><p>No payment will be retried or recovered by this action.</p><small className={states[selected.transaction_id] === "queued" ? "on" : ""}>Queued → Processing → Recovery attempt recommended</small></div><div className="modal-actions"><button onClick={() => update(selected.transaction_id, "reviewed")}>Mark as reviewed</button><button className="primary" onClick={() => update(selected.transaction_id, "queued")} disabled={states[selected.transaction_id] === "queued"}>{states[selected.transaction_id] === "queued" ? "Recovery queued" : "Queue recovery"}</button></div></section></div>}
  </div>;
}
function Metric({ title, value, note, type = "" }) { return <article className={`metric ${type}`}><p>{title}</p><h3>{value}</h3>{note && <small>{note}</small>}</article>; }
